import { useNavigate } from "react-router-dom";
import { useTheme } from "../ThemeContext";

export default function LandingPage() {
  const navigate = useNavigate();
  const { theme, toggle: toggleTheme } = useTheme();

  return (
    <div className="flex min-h-screen flex-col bg-slate-100 dark:bg-slate-950">
      {/* Nav */}
      <nav className="flex items-center justify-between border-b border-slate-200 bg-slate-50 px-8 py-4 dark:border-slate-700 dark:bg-slate-900">
        <div className="flex items-center gap-2">
          <img src="/icon.png" alt="Open Attend" className="h-9 w-9 rounded-lg" />
          <span className="text-xl font-bold text-slate-900 dark:text-slate-100">Open Attend</span>
        </div>
        <div className="flex items-center gap-3">
          <span className="text-xs text-slate-400 dark:text-slate-500">
            Agentic Clinical Decision Support
          </span>
          <button
            onClick={toggleTheme}
            className="flex h-8 w-8 items-center justify-center rounded-lg text-slate-500 transition-colors hover:bg-slate-200 dark:text-slate-400 dark:hover:bg-slate-700"
            title={theme === "dark" ? "Switch to light mode" : "Switch to dark mode"}
          >
            {theme === "dark" ? (
              <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" d="M12 3v2.25m6.364.386-1.591 1.591M21 12h-2.25m-.386 6.364-1.591-1.591M12 18.75V21m-4.773-4.227-1.591 1.591M5.25 12H3m4.227-4.773L5.636 5.636M15.75 12a3.75 3.75 0 1 1-7.5 0 3.75 3.75 0 0 1 7.5 0Z" />
              </svg>
            ) : (
              <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" d="M21.752 15.002A9.72 9.72 0 0 1 18 15.75c-5.385 0-9.75-4.365-9.75-9.75 0-1.33.266-2.597.748-3.752A9.753 9.753 0 0 0 3 11.25C3 16.635 7.365 21 12.75 21a9.753 9.753 0 0 0 9.002-5.998Z" />
              </svg>
            )}
          </button>
        </div>
      </nav>

      {/* Centered disclaimer */}
      <main className="flex flex-1 items-center justify-center px-6">
        <div className="w-full max-w-lg text-center">
          <img src="/icon.png" alt="Open Attend" className="mb-8 h-16 w-16 mx-auto rounded-2xl" />

          <h1 className="mb-3 text-2xl font-bold text-slate-900 dark:text-slate-100">
            Before you begin
          </h1>

          <div className="mb-8 rounded-lg border border-slate-200 bg-white p-5 text-left dark:border-slate-700 dark:bg-slate-800">
            <p className="text-sm leading-relaxed text-slate-600 dark:text-slate-300">
              Open Attend is an <strong className="dark:text-slate-100">AI clinical support tool</strong>, not a
              substitute for clinical judgment. All documentation, codes, alerts,
              and suggestions are generated by AI and must be reviewed by the
              treating physician before use. No patient data leaves your
              device — all inference runs locally with encryption at rest.
            </p>
          </div>

          <button
            onClick={() => navigate("/dashboard")}
            className="btn-primary w-full !py-3 text-base"
          >
            Accept & Continue
          </button>
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-slate-200 bg-slate-50 px-8 py-4 dark:border-slate-700 dark:bg-slate-900">
        <div className="flex items-center justify-between text-xs text-slate-400 dark:text-slate-500">
          <span>
            Built with Google HAI-DEF models: MedGemma, MedASR, MedSigLIP
          </span>
          <span>Not for clinical use without physician oversight</span>
        </div>
      </footer>
    </div>
  );
}
